// <auto-generated />
using System;
using LinkHarvester.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinkHarvester.Persistence.Migrations
{
    [DbContext(typeof(HarvesterDbContext))]
    [Migration("20260529222930_AddCatalogLinkCompositeIndex")]
    partial class AddCatalogLinkCompositeIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("LinkHarvester.Persistence.AppSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioPreference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthPasswordEncrypted")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthUsername")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("HosterPriorityCsv")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlexBaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlexTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityPreferenceCsv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScanIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ScanOnStartup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SynologyAnimeDestination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SynologyBaseUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SynologyConnectionMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SynologyMovieDestination")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SynologyOtpCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SynologyPasswordEncrypted")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("SynologyQuickConnectId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SynologyResolvedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SynologyResolvedBaseUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SynologySeriesDestination")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SynologyUsername")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramBotTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramOwnerChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbApiKeyEncrypted")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbEnrichmentConcurrency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TmdbEnrichmentEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraktClientIdEncrypted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.ArticleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AggregatorDlProtectUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Codec")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("DiscoveredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityLabel")
                        .HasColumnType("TEXT");

                    b.Property<int>("QualityScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResolutionAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ResolvedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTier")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SubmittedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TitleId");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique();

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.CapSolverSpendEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SpentUsd")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("CapSolverSpends");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.Catalog.BackfillRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Discovered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Enriched")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FromDate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Healthy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("LastCompletedPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSeenArticleExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Promoted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skipped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("StartPage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "Kind", "StartedAt");

                    b.ToTable("BackfillRuns");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.Catalog.CatalogEpisodeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpisodeName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpisodePoster")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFullSeason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TitleId", "SeasonNumber", "EpisodeNumber", "IsFullSeason")
                        .IsUnique();

                    b.ToTable("CatalogEpisodes");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.Catalog.CatalogImportRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("FailedRecords")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InsertedEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InsertedLinks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InsertedTitles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDescription")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalRecords")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("CatalogImportRuns");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.Catalog.CatalogLinkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioLangs")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExternalLinkId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HarvesterArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HealthCheckedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HealthSignature")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthStatus")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedHost")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubLangs")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("TitleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("ExternalLinkId")
                        .IsUnique();

                    b.HasIndex("HarvesterArticleId");

                    b.HasIndex("HealthStatus");

                    b.HasIndex("LinkSource");

                    b.HasIndex("NormalizedHost");

                    b.HasIndex("QualityName");

                    b.HasIndex("TitleId");

                    b.HasIndex("TitleId", "NormalizedHost", "QualityName");

                    b.ToTable("CatalogLinks");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.Catalog.CatalogTitleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirstSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HiddenReason")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LinkCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitlePoster")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalKey")
                        .IsUnique();

                    b.HasIndex("CategoryName");

                    b.HasIndex("ImdbId");

                    b.HasIndex("IsHidden");

                    b.HasIndex("NormalizedTitle");

                    b.HasIndex("TmdbId");

                    b.ToTable("CatalogTitles");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.Catalog.CatalogTitleMetadataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnrichmentSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("GenresJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastAirDate")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastEnrichedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MetadataUncertain")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NextEpisodeAirDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NextEpisodeCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLanguage")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Popularity")
                        .HasColumnType("REAL");

                    b.Property<string>("ReleaseDate")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("TitleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("VoteAverage")
                        .HasColumnType("REAL");

                    b.Property<int?>("VoteCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnrichmentSource");

                    b.HasIndex("Popularity");

                    b.HasIndex("TitleId")
                        .IsUnique();

                    b.HasIndex("VoteAverage");

                    b.HasIndex("Year");

                    b.ToTable("CatalogTitleMetadata");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.Catalog.DiscoveryEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogTitleId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FetchedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FetchedAt");

                    b.HasIndex("CatalogTitleId", "Source")
                        .IsUnique();

                    b.HasIndex("Source", "Rank");

                    b.ToTable("DiscoveryEntries");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.Catalog.FollowingDetectionLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CatalogLinkId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogTitleId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ConsumedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConsumedBy")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("DetectedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpisodeCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CatalogTitleId");

                    b.HasIndex("CatalogTitleId", "EpisodeCode")
                        .IsUnique();

                    b.HasIndex("ConsumedAt", "DetectedAt");

                    b.ToTable("FollowingDetectionLog");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.Catalog.FollowingDismissalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatalogTitleId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DismissedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CatalogTitleId")
                        .IsUnique();

                    b.ToTable("FollowingDismissals");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.Catalog.HealthSweepRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Alive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Checked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HiddenTitles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HosterFilter")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("LastCheckedCatalogLinkId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Unknown")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("HealthSweepRuns");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.ResolvedLinkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodeIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hoster")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("ResolvedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("ResolvedLinks");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.ScanRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Discovered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Failed")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewArticles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Resolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "StartedAt");

                    b.ToTable("ScanRuns");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.SubmissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatalogLinkIdsJson")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CatalogTitleId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destination")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DsmErrorCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DsmFailedUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("DsmTaskIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResendOfSubmissionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SubmittedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubmittedUrlsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UrlCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("CatalogTitleId");

                    b.HasIndex("Source", "SubmittedAt");

                    b.HasIndex("Status", "SubmittedAt");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.TitleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BestSubmittedQualityScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Canonical")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CatalogPromotedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CatalogTitleId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Canonical")
                        .IsUnique();

                    b.HasIndex("CatalogTitleId");

                    b.HasIndex("Status", "UpdatedAt");

                    b.HasIndex("NormalizedTitle", "Year", "Kind", "SeasonNumber");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.ArticleEntity", b =>
                {
                    b.HasOne("LinkHarvester.Persistence.TitleEntity", "Title")
                        .WithMany("Articles")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.Catalog.CatalogEpisodeEntity", b =>
                {
                    b.HasOne("LinkHarvester.Persistence.Catalog.CatalogTitleEntity", "Title")
                        .WithMany("Episodes")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.Catalog.CatalogLinkEntity", b =>
                {
                    b.HasOne("LinkHarvester.Persistence.Catalog.CatalogEpisodeEntity", "Episode")
                        .WithMany("Links")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LinkHarvester.Persistence.Catalog.CatalogTitleEntity", "Title")
                        .WithMany("Links")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.Catalog.CatalogTitleMetadataEntity", b =>
                {
                    b.HasOne("LinkHarvester.Persistence.Catalog.CatalogTitleEntity", "Title")
                        .WithOne("Metadata")
                        .HasForeignKey("LinkHarvester.Persistence.Catalog.CatalogTitleMetadataEntity", "TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.ResolvedLinkEntity", b =>
                {
                    b.HasOne("LinkHarvester.Persistence.ArticleEntity", "Article")
                        .WithMany("ResolvedLinks")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.SubmissionEntity", b =>
                {
                    b.HasOne("LinkHarvester.Persistence.ArticleEntity", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Article");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.ArticleEntity", b =>
                {
                    b.Navigation("ResolvedLinks");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.Catalog.CatalogEpisodeEntity", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.Catalog.CatalogTitleEntity", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("Links");

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("LinkHarvester.Persistence.TitleEntity", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
